### ISSUE TITLE
Přidat přehled seriálů

### ISSUE THREAD

**Issue by zoul** [Ohlasy/web#34]
Jednoduchý speciál. Nejspíš vypsat rovnou všechny díly.

**Comment by zoul** [comment]
Mám [první nástřel](http://www.ohlasy.info/special/serialy/). Nejsou tam všechny díly, ale pořád je to velký krok kupředu, pokud jde o viditelnost starších dílů. Jsem v pokušení zbytek dílů řešit odkazem do archivu. (Ale stejně ještě nemám jasno, co s ním bude, viz #2.)

@ttrumpes, říkal jsem si, že bychom mohli na tenhle rozcestník přidat úvodní texty jednotlivých seriálů a krátkou informaci o jejich autorovi. Výhody: zbavili bychom se opakování úvodního textu u každého dílu, které mně vadí. Taky bychom trochu rozdělili tenhle rozcestník, aby nebyl jednolitým proudem náhledů. Nevýhodou je, že už by ten rozcestník byl dost dlouhý. Co myslíš?

**Comment by ttrumpes** [comment]
asi si neumím přesně představit, jak by to vypadalo, ale ta myšlenka se mi dost líbí.

**Comment by zoul** [comment]
Mrkni, nahodil jsem první verzi. Mně se to moc líbí, akorát to chce ještě zapracovat na typografii těch úvodních textů. Jak jsou nestejně dlouhé, zdaleka ne všem sluší sazba na sloupce – to bych nějak domyslel.

**Comment by ttrumpes** [comment]
taky se mi to moc líbí, vlastně ani ta různost textů mě tak neruší.

**Comment by zoul** [comment]
Zkusil jsem text stáhnout na dva sloupce, tím už nevypadá tak divně, když je rozdělený na tři prcky. Akorát ten Hynkův úvodní text bychom mohli prokrátit? Klidně bych smahl první odstavec. A ještě zvažuju, jak z náhledů článků na téhle stránce odstranit prefixy s názvem seriálu, který se tu blbě opakuje. Jinak myslím na první verzi dobrý.
