### ISSUE TITLE
Promovat předplatné přímo u článků

### ISSUE THREAD

**Issue by zoul** [Ohlasy/web#40]
Guardian se s tím v poslední době nemaže:

![reklamní banner Guardianu](https://cloud.githubusercontent.com/assets/95329/26027394/88cd5d78-380d-11e7-9b71-ec7f21b64678.png)

Na konci článku pak mají drobnější upoutávku:

![příklad upoutávky na konci článků](https://cloud.githubusercontent.com/assets/95329/26027396/9b17967e-380d-11e7-9ef4-e6553bd924b6.png)

(_Když už jste tady… chtěli bychom vás poprosit o malou laskavost. Guardian dnes má mnohem více čtenářů, než měl dříve, ale mnohem méně platících. Příjmy z reklamy všem médiím klesají. A narozdíl od jiných novin jsme nezavedli paywall, protože chceme udržet naši novinařinu tak otevřenou, jak to jen půjde. Takže už asi tušíte, jakou laskavost bychom od vás chtěli. Nezávislá investigativní žurnalistika Guardianu vyžaduje hodně času, peněz a tvrdé práce. Ale děláme ji, protože si myslíme, že náš úhel pohledu je důležitý – a mohl by se krýt s tím vaším. Kdyby nás každý, kdo nás čte a oceňuje, také platil, naše budoucnost by byla mnohem růžovější._)

@ttrumpes, navrhněme nějaký stručný text, který bychom za naše články strčili též.

**Comment by ttrumpes** [comment]
No to je skvělé, jsem určitě pro.

**Comment by zoul** [comment]
Vykopávám: _Provoz kvalitních novin, kterými se snažíme být, vyžaduje hodně práce a peněz. Ohlasy už druhým rokem dotujeme z vlastní kapsy, protože v nich vidíme smysl a možnost zlepšit život v našem regionu. Našli jsme dostatek čtenářů, kteří mají o naše texty zájem, ale zatím jen málo těch, kteří by nám přispěli finančně. Jestli naše texty rádi čtete, zvažte prosím [pořízení předplatného](http://predplatne.ohlasy.info). Můžete si nás předplatit na webu i na papíře; bez dostatečného počtu platících čtenářů zanikneme._

**Comment by zoul** [comment]
Takhle by to vypadalo naživo:

![ukázka reklamy](https://cloud.githubusercontent.com/assets/95329/26027544/0b6afdd8-3810-11e7-9d14-03688b6c8855.png)

**Comment by ttrumpes** [comment]
Trochu jsem upravil. 
Nebylo by dobré oddělit to ještě nějakou čárou? Ať je přeci jen jasný konec článku.

*Provoz novin vyžaduje hodně práce a peněz. Ohlasy už třetím rokem dotujeme z vlastní kapsy, protože v nich vidíme smysl a možnost zlepšit život v našem regionu. Vedle toho fungujeme i díky maximální skromnosti a vstřícnosti našich autorů. Našli jsme dostatek čtenářů, kteří mají o naše texty zájem, ale zatím jen málo těch, kteří by nám přispěli finančně. Navzdory tomu ale nechceme naše texty uzamykat jen pro platící, záleží nám na tom, aby se dostali k co největšímu počtu čtenářů. Jestli nás rádi čtete, zvažte prosím pořízení předplatného. Můžete si nás předplatit na webu i na papíře; bez dostatečného počtu platících čtenářů zanikneme.*

**Comment by ttrumpes** [comment]
možná ještě *prosíme zvažte* – ať zůstaneme v plurálu

**Comment by zoul** [comment]
Čáru udělám, souhlas. Prosíme bych nechal klidně v singuláru. Zmínku o autorech kvituju, ale už je to dost dlouhý, není? Zmínka o paywallu je výborná a dal bych jí přednost před autory.

**Comment by ttrumpes** [comment]
Souhlas. Autory oželím :) Upravil jsem trochu i ten úvod, mám trochu strach, aby to nevypadalo blbě, že sami sebe pasujeme na kvalitní žurnalistiku.

**Comment by zoul** [comment]
Hotovo, visí 🚀 . Kdyby se nám to nějak rozleželo, můžeme upravit. Statistiky sledujeme.

**Comment by ttrumpes** [comment]
Paráda. Dobrá věc.
